pipeline {
    agent any

    environment {
        NETLIFY_SITE_ID = credentials('netlify-site-id')
        NETLIFY_AUTH_TOKEN = credentials('netlify-token')
    }

    stages {
        stage('Build') {
            agent {
                docker {
                    image 'node:18-alpine'
                    reuseNode true
                }
            }
            steps {
                dir('jenkins-v2/app')
                {
                    sh '''
                        ls -la
                        node --version
                        npm --version
                        npm ci
                        npm run build
                        ls -la
                    '''
                }
            }
        }
        stage('Run Test')
        {
            parallel {
                stage('Test 1') {
                    agent {
                        docker {
                            image 'node:18-alpine'
                            reuseNode true
                        }
                    }
                    steps {
                        echo "Test stage"
                        sh '''
                            ls -l
                            test -f jenkins-v2/app/.next/server/pages/index-v2.html
                        '''
                    }
                }
                stage('Test 2') {
                    agent {
                        docker {
                            image 'node:18-alpine'
                            reuseNode true
                        }
                    }
                    steps {
                        echo "Test stage"
                        sh '''
                            ls -l
                            cd jenkins-v2/app && npm test
                        '''
                    }
                }
            }
        }
        stage('Deploy') {
                    agent {
                        docker {
                            image 'node:18-alpine'
                            reuseNode true
                        }
                    }
                    steps {
                        dir('jenkins-v2/app')
                        {
                            sh '''
                                npm install netlify-cli
                                node_modules/.bin/netlify --version
                                node_modules/.bin/netlify status
                                node_modules/.bin/netlify deploy --dir=.next --prod
                            '''
                        }
                    }
                }
    }
    post {
        always {
            junit 'jenkins-v2/app/reports/junit.xml'
        }
    }
}