pipeline {
    agent any

    stages {
        stage('Build') {
            agent {
                docker {
                    image 'node:18-alpine'
                    reuseNode true
                }
            }
            steps {
                dir('jenkins-v2/app')
                {
                    sh '''
                        ls -la
                        node --version
                        npm --version
                        npm ci
                        npm run build
                        ls -la
                    '''
                }
            }
        }
        stage('Test') {
            agent {
                docker {
                    image 'node:18-alpine'
                    reuseNode true
                }
            }
            steps {
                echo "Test stage"
                sh '''
                    ls -l
                    test -f jenkins-v2/app/.next/server/pages/index-v2.html
                    cd jenkins-v2/app && npm test
                '''
            }
        }
        stage('End to end') {
            agent {
                docker {
                    image 'mcr.microsoft.com/playwright:v1.49.1-noble'
                    reuseNode true
                }
            }
            steps {
                dir('jenkins-v2/app') {
                    echo 'End to end stage'
                    sh '''
                        npm install -g serve
                        serve -s build
                        npx playwright test
                    '''
                }
            }
        }
    }
    post {
        always {
            junit 'jenkins-v2/app/reports/junit.xml'
        }
    }
}