services:
  jenkins:
    container_name: jenkins
    image: jenkins-ansible
    build:
      context: jenkins-ansible
    ports:
      - "8080:8080"
    volumes:
      - "$PWD/jenkins-home:/var/jenkins_home"
    networks:
      - net
  remote_host:
    container_name: remote-host
    image: remote-host
    build:
      context: production-1
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
      - MYSQL_PASS=${MYSQL_PASS}
      - MYSQL_DB_CONTAINER=${MYSQL_DB_CONTAINER}
      - MYSQL_DB_NAME=${MYSQL_DB_NAME}
    networks:
      - net
  db_host:
    container_name: mysql-db
    image: mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=1234"
    volumes:
      - "$PWD/mysql-db-data:/var/lib/mysql"
    networks:
      - net
  gitlab:
    image: gitlab/gitlab-ee:latest
    container_name: git-server
    platform: linux/amd64
    hostname: 'gitlab.example.com'
    ports:
      - '8090:80'
    volumes:
      - "$PWD/git-server/config:/etc/gitlab"
      - "$PWD/git-server/logs:/var/log/gitlab"
      - "$PWD/git-server/data:/var/opt/gitlab"
    shm_size: '256m'
    networks:
      - net

networks:
  net:

